### PR TITLE
Technical Debt Fixes for Case Study 1 - Group 10

### PR DESCRIPTION
**Pull request by 0matleb2**
# Technical Debt Fixes for Case Study 1 - Group 10

This PR addresses several technical debt issues identified in Case Study 1 for Group 10 and merges the following changes from our group fork to the main fork. These fixes aim to improve code quality by refactoring methods, reducing duplication, and enhancing code maintainability.

### Refactor `Battle::shutdownTurn()` Method to Reduce Cognitive Complexity
- Refactored the `shutdownTurn()` method in the `Battle` class to reduce cognitive complexity, making it more maintainable and readable.  
  **Issue:** soen6431group10/robocodeFall2024#1  
  **PR:** soen6431group10/robocodeFall2024#2  

### Reduce Duplication of Literal `[^0-9.]` in `Battle.java`
- Refactored the regular expression literal to reduce duplication and improve maintainability.  
  **Issue:** soen6431group10/robocodeFall2024#6  
  **PR:** soen6431group10/robocodeFall2024#7  

### Use of Diamond Operator in Generic Type Initialization
- Improved the code by applying the diamond operator in generic type initialization, enhancing readability and maintainability.  
  **Issue:** soen6431group10/robocodeFall2024#10  
  **PR:** soen6431group10/robocodeFall2024#11  

### Define Constant for the Literal `"robots"`
- Refactored code to define a constant instead of duplicating the literal `"robots"` three times, following best practices.  
  **Issue:** soen6431group10/robocodeFall2024#4  
  **PR:** soen6431group10/robocodeFall2024#5  

### Refactor Code Smell in `FileUtil.java`
- Refactored the identified code smell in `FileUtil.java` to improve code quality and reduce technical debt.  
  **Issue:** soen6431group10/robocodeFall2024#12  
  **PR:** soen6431group10/robocodeFall2024#13

### CODE REVIEW

**Comment by chiragmdeekshith** [comment]
Hello, I noticed that the [soen6431group10:main](https://github.com/soen6431group10/robocodeFall2024/tree/main) fork does not have "Workflows" enabled. Please enable it on your fork to ensure the build passes before pushing it to the parent repository.

**Comment by rkerw** [comment]
It seems the most recent build is failing due to this merge, additional PRs cannot be merged automatically until it is fixed @0matleb2

**Comment by 0matleb2** [comment]
@rkerw The build was already failing before this PR merged due to merge commits pushed by @melisa1026 directly to the main branch.

**Comment by melisa1026** [comment]
Oh...I didn't realize, very sorry:'( I don't know why, but my fork wasn't appearing when i tried to make a pull request, I will try to fix ASAP

**Comment by chiragmdeekshith** [comment]
There's a common discord server for everyone assigned to the RoboCode repository. Let's discuss this over there and try to get this working before midnight. 

[Discord server](https://discord.gg/ZgTqBb4j) - Valid for 7 days

**Pull request merged**
